services:
  frontend:
    image: vrisa-frontend:1.0.0
    container_name: vrisa-frontend
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "8088:5173"
    environment:
      - VITE_API_URL=http://localhost:8000/api
    restart: always